[2023-12-26T08:09:18.046+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: potential_customers_process.create_customers_table scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T08:09:18.087+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: potential_customers_process.create_customers_table scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T08:09:18.088+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T08:09:18.089+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-12-26T08:09:18.090+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T08:09:18.125+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_customers_table> on 2023-12-25 00:00:00+00:00
[2023-12-26T08:09:18.160+0000] {standard_task_runner.py:55} INFO - Started process 275 to run task
[2023-12-26T08:09:18.170+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'potential_customers_process', 'create_customers_table', 'scheduled__2023-12-25T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/potential_customers_process.py', '--cfg-path', '/tmp/tmpjm66537y']
[2023-12-26T08:09:18.190+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask create_customers_table
[2023-12-26T08:09:18.466+0000] {task_command.py:376} INFO - Running <TaskInstance: potential_customers_process.create_customers_table scheduled__2023-12-25T00:00:00+00:00 [running]> on host 992e73c39b9a
[2023-12-26T08:09:18.637+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=potential_customers_process
AIRFLOW_CTX_TASK_ID=create_customers_table
AIRFLOW_CTX_EXECUTION_DATE=2023-12-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-25T00:00:00+00:00
[2023-12-26T08:09:18.678+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-12-26T08:09:18.690+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS customers (
                fullname TEXT NOT NULL,
                country_code TEXT NOT NULL,
                gender TEXT NOT NULL,
                age INT NOT NULL
            );
        , parameters: None
[2023-12-26T08:09:18.738+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=potential_customers_process, task_id=create_customers_table, execution_date=20231225T000000, start_date=20231226T080918, end_date=20231226T080918
[2023-12-26T08:09:18.833+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-12-26T08:09:18.957+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-12-26T10:23:42.387+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: potential_customers_process.create_customers_table scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T10:23:42.393+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: potential_customers_process.create_customers_table scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T10:23:42.393+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T10:23:42.393+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-12-26T10:23:42.393+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T10:23:42.400+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_customers_table> on 2023-12-25 00:00:00+00:00
[2023-12-26T10:23:42.404+0000] {standard_task_runner.py:55} INFO - Started process 129 to run task
[2023-12-26T10:23:42.407+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'potential_customers_process', 'create_customers_table', 'scheduled__2023-12-25T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/potential_customers_process.py', '--cfg-path', '/tmp/tmp2hxpjdgg']
[2023-12-26T10:23:42.407+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask create_customers_table
[2023-12-26T10:23:42.444+0000] {task_command.py:376} INFO - Running <TaskInstance: potential_customers_process.create_customers_table scheduled__2023-12-25T00:00:00+00:00 [running]> on host 886ab54d5808
[2023-12-26T10:23:42.483+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=potential_customers_process
AIRFLOW_CTX_TASK_ID=create_customers_table
AIRFLOW_CTX_EXECUTION_DATE=2023-12-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-25T00:00:00+00:00
[2023-12-26T10:23:42.488+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-12-26T10:23:42.492+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS customers (
                fullname TEXT NOT NULL,
                country_code TEXT NOT NULL,
                gender TEXT NOT NULL,
                age INT NOT NULL,
                last_login INT64 NOT NULL
            );
        , parameters: None
[2023-12-26T10:23:42.493+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedObject: type "int64" does not exist
LINE 7:                 last_login INT64 NOT NULL
                                   ^

[2023-12-26T10:23:42.500+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=potential_customers_process, task_id=create_customers_table, execution_date=20231225T000000, start_date=20231226T102342, end_date=20231226T102342
[2023-12-26T10:23:42.509+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task create_customers_table (type "int64" does not exist
LINE 7:                 last_login INT64 NOT NULL
                                   ^
; 129)
[2023-12-26T10:23:42.543+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-12-26T10:23:42.560+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
