[2023-12-27T16:03:17.493+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: salesforce_contact_processing.extract_user manual__2023-12-27T15:53:03.143350+00:00 [queued]>
[2023-12-27T16:03:17.504+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: salesforce_contact_processing.extract_user manual__2023-12-27T15:53:03.143350+00:00 [queued]>
[2023-12-27T16:03:17.504+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-27T16:03:17.505+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-12-27T16:03:17.505+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-27T16:03:17.517+0000] {taskinstance.py:1383} INFO - Executing <Task(SimpleHttpOperator): extract_user> on 2023-12-27 15:53:03.143350+00:00
[2023-12-27T16:03:17.524+0000] {standard_task_runner.py:55} INFO - Started process 27972 to run task
[2023-12-27T16:03:17.528+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'salesforce_contact_processing', 'extract_user', 'manual__2023-12-27T15:53:03.143350+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/salesforce_contact_processing.py', '--cfg-path', '/tmp/tmpsmzlwmb2']
[2023-12-27T16:03:17.530+0000] {standard_task_runner.py:83} INFO - Job 36: Subtask extract_user
[2023-12-27T16:03:17.581+0000] {task_command.py:376} INFO - Running <TaskInstance: salesforce_contact_processing.extract_user manual__2023-12-27T15:53:03.143350+00:00 [running]> on host bbee0f1e1252
[2023-12-27T16:03:17.617+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=salesforce_contact_processing
AIRFLOW_CTX_TASK_ID=extract_user
AIRFLOW_CTX_EXECUTION_DATE=2023-12-27T15:53:03.143350+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-27T15:53:03.143350+00:00
[2023-12-27T16:03:17.618+0000] {http.py:121} INFO - Calling HTTP method
[2023-12-27T16:03:17.633+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 123, in execute
    response = http.run(self.endpoint, self.data, self.headers, self.extra_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 128, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 82, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `user_api` isn't defined
[2023-12-27T16:03:17.636+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=salesforce_contact_processing, task_id=extract_user, execution_date=20231227T155303, start_date=20231227T160317, end_date=20231227T160317
[2023-12-27T16:03:17.642+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 36 for task extract_user (The conn_id `user_api` isn't defined; 27972)
[2023-12-27T16:03:17.660+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-12-27T16:03:17.671+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
