[2023-12-26T08:09:56.536+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: potential_customers_process.is_api_available manual__2023-12-26T08:09:52.928490+00:00 [queued]>
[2023-12-26T08:09:56.542+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: potential_customers_process.is_api_available manual__2023-12-26T08:09:52.928490+00:00 [queued]>
[2023-12-26T08:09:56.543+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T08:09:56.543+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-12-26T08:09:56.543+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T08:09:56.551+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-12-26 08:09:52.928490+00:00
[2023-12-26T08:09:56.557+0000] {standard_task_runner.py:55} INFO - Started process 314 to run task
[2023-12-26T08:09:56.560+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'potential_customers_process', 'is_api_available', 'manual__2023-12-26T08:09:52.928490+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/potential_customers_process.py', '--cfg-path', '/tmp/tmpp9fkin2c']
[2023-12-26T08:09:56.562+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask is_api_available
[2023-12-26T08:09:56.604+0000] {task_command.py:376} INFO - Running <TaskInstance: potential_customers_process.is_api_available manual__2023-12-26T08:09:52.928490+00:00 [running]> on host 992e73c39b9a
[2023-12-26T08:09:56.645+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=potential_customers_process
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-12-26T08:09:52.928490+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-26T08:09:52.928490+00:00
[2023-12-26T08:09:56.646+0000] {http.py:120} INFO - Poking: api/
[2023-12-26T08:09:56.658+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 189, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 135, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 126, in poke
    extra_options=self.extra_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 128, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 82, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `user_api` isn't defined
[2023-12-26T08:09:56.661+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=potential_customers_process, task_id=is_api_available, execution_date=20231226T080952, start_date=20231226T080956, end_date=20231226T080956
[2023-12-26T08:09:56.667+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 7 for task is_api_available (The conn_id `user_api` isn't defined; 314)
[2023-12-26T08:09:56.695+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-12-26T08:09:56.717+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
